alias 'c'='clear'
alias 'vim'='nvim'
alias 'vim.'='vim .'
alias 'lg'='lazygit'
alias 'ls'='eza --icons=auto'
alias 'll'='ls -l'
alias 'la'='ll -A'
alias 'man'='batman'
alias 'hf'='hyfetch'
alias 'svim'='sudoedit'
